name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: List
        run: ls -lahG